// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ButtonController from "./button_controller"
application.register("button", ButtonController)

import CategoryButtonsScrollDownController from "./category_buttons_scroll_down_controller"
application.register("category-buttons-scroll-down", CategoryButtonsScrollDownController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProfilController from "./profil_controller"
application.register("profil", ProfilController)

import ProfilToEmailController from "./profil_to_email_controller"
application.register("profil-to-email", ProfilToEmailController)

import ProjectFormController from "./project_form_controller"
application.register("project-form", ProjectFormController)

import SketchController from "./sketch_controller"
application.register("sketch", SketchController)

import SortableCardsController from "./sortable_cards_controller"
application.register("sortable-cards", SortableCardsController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import TopProjectController from "./top_project_controller"
application.register("top-project", TopProjectController)
