// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ButtonController from "./button_controller"
application.register("button", ButtonController)

import CategoryButtonsScrollDownController from "./category_buttons_scroll_down_controller"
application.register("category-buttons-scroll-down", CategoryButtonsScrollDownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProfilToEmailController from "./profil_to_email_controller"
application.register("profil-to-email", ProfilToEmailController)

import SketchController from "./sketch_controller"
application.register("sketch", SketchController)

import TopProjectController from "./top_project_controller"
application.register("top-project", TopProjectController)
 