meta_name: "L'Accroche"
meta_title: "L'Accroche - creates your musical network"
meta_description: "Get in touch with a community of music makers, editors and artists"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@your_twitter_account"   # required for Twitter Cards
