meta_name: "L'Accroche - create your musical network"
meta_title: "L'Accroche"
meta_description: "Get in touch with a community of music makers, editors and artists"
meta_image: "accroche_card_rsx.png" # should exist in `app/assets/images/`
twitter_account: "@your_twitter_account"   # required for Twitter Cards
